services:
  reverse_proxy:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth_service
      - user_service

  auth_service_database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: auth_service
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s

  auth_service:
    build:
      context: auth_service
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3000/api/auth_service/v1/health",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
    depends_on:
      auth_service_database:
        condition: service_healthy
    volumes:
      - ./auth_service:/app
      - /app/node_modules

  user_service_database:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "user_service"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s

  user_service:
    build:
      context: user_service
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/user_service/v1/health",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
    depends_on:
      user_service_database:
        condition: service_healthy
    volumes:
      - ./user_service:/app
      - /app/vendor

volumes:
  mysql-db:
  postgres-db:
