### Auth service

@baseUrl =  http://localhost/api
@auth = auth_service/v1

### Health check
GET {{baseUrl}}/{{auth}}/health

### Register
# @name register
POST {{baseUrl}}/{{auth}}/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}

### Get token
@token = {{ register.response.body.data.accessToken }}
@refresh = {{ register.response.body.data.refreshToken }}

### Login
# @name login
POST {{baseUrl}}/{{auth}}/login
Content-Type: application/json

{
    "email": "test5@test.com",
    "password": "12345678"
}

### Get token
@token = {{ login.response.body.data.accessToken }}
@refresh = {{ login.response.body.data.refreshToken }}

### Logout
GET {{baseUrl}}/{{auth}}/logout
Content-Type: application/json
Authorization: Bearer {{ token }}

### Refresh
POST {{baseUrl}}/{{auth}}/refresh
Content-Type: application/json

{
  "token": "{{ refresh }}"
}

### Me
GET {{baseUrl}}/{{auth}}/me
Content-Type: application/json
Authorization: Bearer {{ token }}

### Verify
GET {{baseUrl}}/{{auth}}/verify-token
Content-Type: application/json
Authorization: Bearer {{ token }}

### User service

@user = user_service/v1

### Health check
GET {{baseUrl}}/{{user}}/health

### Create or update user
POST {{baseUrl}}/{{user}}/profiles
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "first_name": "Manh",
    "last_name": "Pham",
    "phone": "0972004788",
    "address": "HN"
}

### me
GET {{baseUrl}}/{{user}}/profiles
Content-Type: application/json
Authorization: Bearer {{ token }}

### Get user by id
GET {{baseUrl}}/{{user}}/profiles/1
Content-Type: application/json
Authorization: Bearer {{ token }}

### Shop service

@shop = shop_service/v1

### Health check
GET {{baseUrl}}/{{shop}}/health

### Product service

@product = product_service/v1

### Health check
GET {{baseUrl}}/{{product}}/health

### Get products
GET {{baseUrl}}/{{product}}/products